// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: basket_confirmed.proto

package basketconfirmed

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BasketConfirmedIntegrationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BasketId      string                 `protobuf:"bytes,1,opt,name=basketId,proto3" json:"basketId,omitempty"`
	Address       *Address               `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasketConfirmedIntegrationEvent) Reset() {
	*x = BasketConfirmedIntegrationEvent{}
	mi := &file_basket_confirmed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasketConfirmedIntegrationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasketConfirmedIntegrationEvent) ProtoMessage() {}

func (x *BasketConfirmedIntegrationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_basket_confirmed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasketConfirmedIntegrationEvent.ProtoReflect.Descriptor instead.
func (*BasketConfirmedIntegrationEvent) Descriptor() ([]byte, []int) {
	return file_basket_confirmed_proto_rawDescGZIP(), []int{0}
}

func (x *BasketConfirmedIntegrationEvent) GetBasketId() string {
	if x != nil {
		return x.BasketId
	}
	return ""
}

func (x *BasketConfirmedIntegrationEvent) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Street        string                 `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	House         string                 `protobuf:"bytes,4,opt,name=house,proto3" json:"house,omitempty"`
	Apartment     string                 `protobuf:"bytes,5,opt,name=apartment,proto3" json:"apartment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_basket_confirmed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_basket_confirmed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_basket_confirmed_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetHouse() string {
	if x != nil {
		return x.House
	}
	return ""
}

func (x *Address) GetApartment() string {
	if x != nil {
		return x.Apartment
	}
	return ""
}

var File_basket_confirmed_proto protoreflect.FileDescriptor

const file_basket_confirmed_proto_rawDesc = "" +
	"\n" +
	"\x16basket_confirmed.proto\x12\x0fBasketConfirmed\"q\n" +
	"\x1fBasketConfirmedIntegrationEvent\x12\x1a\n" +
	"\bbasketId\x18\x01 \x01(\tR\bbasketId\x122\n" +
	"\aAddress\x18\x02 \x01(\v2\x18.BasketConfirmed.AddressR\aAddress\"\x83\x01\n" +
	"\aAddress\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x16\n" +
	"\x06street\x18\x03 \x01(\tR\x06street\x12\x14\n" +
	"\x05house\x18\x04 \x01(\tR\x05house\x12\x1c\n" +
	"\tapartment\x18\x05 \x01(\tR\tapartmentb\x06proto3"

var (
	file_basket_confirmed_proto_rawDescOnce sync.Once
	file_basket_confirmed_proto_rawDescData []byte
)

func file_basket_confirmed_proto_rawDescGZIP() []byte {
	file_basket_confirmed_proto_rawDescOnce.Do(func() {
		file_basket_confirmed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_basket_confirmed_proto_rawDesc), len(file_basket_confirmed_proto_rawDesc)))
	})
	return file_basket_confirmed_proto_rawDescData
}

var file_basket_confirmed_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_basket_confirmed_proto_goTypes = []any{
	(*BasketConfirmedIntegrationEvent)(nil), // 0: BasketConfirmed.BasketConfirmedIntegrationEvent
	(*Address)(nil),                         // 1: BasketConfirmed.Address
}
var file_basket_confirmed_proto_depIdxs = []int32{
	1, // 0: BasketConfirmed.BasketConfirmedIntegrationEvent.Address:type_name -> BasketConfirmed.Address
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_basket_confirmed_proto_init() }
func file_basket_confirmed_proto_init() {
	if File_basket_confirmed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_basket_confirmed_proto_rawDesc), len(file_basket_confirmed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_basket_confirmed_proto_goTypes,
		DependencyIndexes: file_basket_confirmed_proto_depIdxs,
		MessageInfos:      file_basket_confirmed_proto_msgTypes,
	}.Build()
	File_basket_confirmed_proto = out.File
	file_basket_confirmed_proto_goTypes = nil
	file_basket_confirmed_proto_depIdxs = nil
}
