with-expecter: True
dir: mocks/{{ replaceAll .PackagePath "internal" "internal_" }}
packages:
  github.com/victor-tsykanov/delivery/internal/common/eventdispatcher:
    interfaces:
      IEventDispatcher:
  github.com/victor-tsykanov/delivery/internal/common/persistence:
    interfaces:
      ITransactionManager:
  github.com/victor-tsykanov/delivery/internal/core/domain/services:
    interfaces:
      IDispatchService:
  github.com/victor-tsykanov/delivery/internal/core/ports/in:
    interfaces:
      ICreateOrderCommandHandler:
      IGetAllCouriersQueryHandler:
      IGetPendingOrdersQueryHandler:
  github.com/victor-tsykanov/delivery/internal/core/ports/out:
    interfaces:
      ICourierRepository:
      IOrderRepository:
      IGeoClient:

