// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: contract.proto

package geopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Geo_GetGeolocation_FullMethodName = "/geo.Geo/GetGeolocation"
)

// GeoClient is the client API for Geo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The Geo service definition.
type GeoClient interface {
	// Get Geolocation
	GetGeolocation(ctx context.Context, in *GetGeolocationRequest, opts ...grpc.CallOption) (*GetGeolocationReply, error)
}

type geoClient struct {
	cc grpc.ClientConnInterface
}

func NewGeoClient(cc grpc.ClientConnInterface) GeoClient {
	return &geoClient{cc}
}

func (c *geoClient) GetGeolocation(ctx context.Context, in *GetGeolocationRequest, opts ...grpc.CallOption) (*GetGeolocationReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGeolocationReply)
	err := c.cc.Invoke(ctx, Geo_GetGeolocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeoServer is the server API for Geo service.
// All implementations must embed UnimplementedGeoServer
// for forward compatibility.
//
// The Geo service definition.
type GeoServer interface {
	// Get Geolocation
	GetGeolocation(context.Context, *GetGeolocationRequest) (*GetGeolocationReply, error)
	mustEmbedUnimplementedGeoServer()
}

// UnimplementedGeoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGeoServer struct{}

func (UnimplementedGeoServer) GetGeolocation(context.Context, *GetGeolocationRequest) (*GetGeolocationReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGeolocation not implemented")
}
func (UnimplementedGeoServer) mustEmbedUnimplementedGeoServer() {}
func (UnimplementedGeoServer) testEmbeddedByValue()             {}

// UnsafeGeoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeoServer will
// result in compilation errors.
type UnsafeGeoServer interface {
	mustEmbedUnimplementedGeoServer()
}

func RegisterGeoServer(s grpc.ServiceRegistrar, srv GeoServer) {
	// If the following call pancis, it indicates UnimplementedGeoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Geo_ServiceDesc, srv)
}

func _Geo_GetGeolocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGeolocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeoServer).GetGeolocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Geo_GetGeolocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeoServer).GetGeolocation(ctx, req.(*GetGeolocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Geo_ServiceDesc is the grpc.ServiceDesc for Geo service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Geo_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "geo.Geo",
	HandlerType: (*GeoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGeolocation",
			Handler:    _Geo_GetGeolocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "contract.proto",
}
