// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: contract.proto

package geopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request
type GetGeolocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Street        string                 `protobuf:"bytes,1,opt,name=Street,proto3" json:"Street,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGeolocationRequest) Reset() {
	*x = GetGeolocationRequest{}
	mi := &file_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGeolocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeolocationRequest) ProtoMessage() {}

func (x *GetGeolocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeolocationRequest.ProtoReflect.Descriptor instead.
func (*GetGeolocationRequest) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{0}
}

func (x *GetGeolocationRequest) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

// Response
type GetGeolocationReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=Location,proto3" json:"Location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGeolocationReply) Reset() {
	*x = GetGeolocationReply{}
	mi := &file_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGeolocationReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGeolocationReply) ProtoMessage() {}

func (x *GetGeolocationReply) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGeolocationReply.ProtoReflect.Descriptor instead.
func (*GetGeolocationReply) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{1}
}

func (x *GetGeolocationReply) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

// Geolocation
type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{2}
}

func (x *Location) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Location) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_contract_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_contract_proto protoreflect.FileDescriptor

const file_contract_proto_rawDesc = "" +
	"\n" +
	"\x0econtract.proto\x12\x03geo\"/\n" +
	"\x15GetGeolocationRequest\x12\x16\n" +
	"\x06Street\x18\x01 \x01(\tR\x06Street\"@\n" +
	"\x13GetGeolocationReply\x12)\n" +
	"\bLocation\x18\x01 \x01(\v2\r.geo.LocationR\bLocation\"&\n" +
	"\bLocation\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"#\n" +
	"\rErrorResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text2M\n" +
	"\x03Geo\x12F\n" +
	"\x0eGetGeolocation\x12\x1a.geo.GetGeolocationRequest\x1a\x18.geo.GetGeolocationReplyB\x1bZ\fgeosrv/geopb\xaa\x02\n" +
	"GeoApp.Apib\x06proto3"

var (
	file_contract_proto_rawDescOnce sync.Once
	file_contract_proto_rawDescData []byte
)

func file_contract_proto_rawDescGZIP() []byte {
	file_contract_proto_rawDescOnce.Do(func() {
		file_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)))
	})
	return file_contract_proto_rawDescData
}

var file_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_contract_proto_goTypes = []any{
	(*GetGeolocationRequest)(nil), // 0: geo.GetGeolocationRequest
	(*GetGeolocationReply)(nil),   // 1: geo.GetGeolocationReply
	(*Location)(nil),              // 2: geo.Location
	(*ErrorResponse)(nil),         // 3: geo.ErrorResponse
}
var file_contract_proto_depIdxs = []int32{
	2, // 0: geo.GetGeolocationReply.Location:type_name -> geo.Location
	0, // 1: geo.Geo.GetGeolocation:input_type -> geo.GetGeolocationRequest
	1, // 2: geo.Geo.GetGeolocation:output_type -> geo.GetGeolocationReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_contract_proto_init() }
func file_contract_proto_init() {
	if File_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_contract_proto_rawDesc), len(file_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_contract_proto_goTypes,
		DependencyIndexes: file_contract_proto_depIdxs,
		MessageInfos:      file_contract_proto_msgTypes,
	}.Build()
	File_contract_proto = out.File
	file_contract_proto_goTypes = nil
	file_contract_proto_depIdxs = nil
}
