// Code generated by mockery v2.52.3. DO NOT EDIT.

package persistence

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockITransactionManager is an autogenerated mock type for the ITransactionManager type
type MockITransactionManager struct {
	mock.Mock
}

type MockITransactionManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITransactionManager) EXPECT() *MockITransactionManager_Expecter {
	return &MockITransactionManager_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, fn
func (_m *MockITransactionManager) Execute(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockITransactionManager_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockITransactionManager_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(context.Context) error
func (_e *MockITransactionManager_Expecter) Execute(ctx interface{}, fn interface{}) *MockITransactionManager_Execute_Call {
	return &MockITransactionManager_Execute_Call{Call: _e.mock.On("Execute", ctx, fn)}
}

func (_c *MockITransactionManager_Execute_Call) Run(run func(ctx context.Context, fn func(context.Context) error)) *MockITransactionManager_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(func(context.Context) error))
	})
	return _c
}

func (_c *MockITransactionManager_Execute_Call) Return(_a0 error) *MockITransactionManager_Execute_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockITransactionManager_Execute_Call) RunAndReturn(run func(context.Context, func(context.Context) error) error) *MockITransactionManager_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockITransactionManager creates a new instance of MockITransactionManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITransactionManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITransactionManager {
	mock := &MockITransactionManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
