// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/basket/queues/basket_confirmed.proto

package basketconfirmedpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BasketConfirmedIntegrationEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BasketId       string                 `protobuf:"bytes,1,opt,name=basketId,proto3" json:"basketId,omitempty"`
	Address        *Address               `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Items          []*Item                `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	DeliveryPeriod *DeliveryPeriod        `protobuf:"bytes,4,opt,name=deliveryPeriod,proto3" json:"deliveryPeriod,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BasketConfirmedIntegrationEvent) Reset() {
	*x = BasketConfirmedIntegrationEvent{}
	mi := &file_api_basket_queues_basket_confirmed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasketConfirmedIntegrationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasketConfirmedIntegrationEvent) ProtoMessage() {}

func (x *BasketConfirmedIntegrationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_basket_queues_basket_confirmed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasketConfirmedIntegrationEvent.ProtoReflect.Descriptor instead.
func (*BasketConfirmedIntegrationEvent) Descriptor() ([]byte, []int) {
	return file_api_basket_queues_basket_confirmed_proto_rawDescGZIP(), []int{0}
}

func (x *BasketConfirmedIntegrationEvent) GetBasketId() string {
	if x != nil {
		return x.BasketId
	}
	return ""
}

func (x *BasketConfirmedIntegrationEvent) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *BasketConfirmedIntegrationEvent) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *BasketConfirmedIntegrationEvent) GetDeliveryPeriod() *DeliveryPeriod {
	if x != nil {
		return x.DeliveryPeriod
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Country       string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	City          string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Street        string                 `protobuf:"bytes,3,opt,name=street,proto3" json:"street,omitempty"`
	House         string                 `protobuf:"bytes,4,opt,name=house,proto3" json:"house,omitempty"`
	Apartment     string                 `protobuf:"bytes,5,opt,name=apartment,proto3" json:"apartment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_api_basket_queues_basket_confirmed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_api_basket_queues_basket_confirmed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_api_basket_queues_basket_confirmed_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Address) GetHouse() string {
	if x != nil {
		return x.House
	}
	return ""
}

func (x *Address) GetApartment() string {
	if x != nil {
		return x.Apartment
	}
	return ""
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	GoodId        string                 `protobuf:"bytes,2,opt,name=goodId,proto3" json:"goodId,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int32                  `protobuf:"varint,5,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_api_basket_queues_basket_confirmed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_api_basket_queues_basket_confirmed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_api_basket_queues_basket_confirmed_proto_rawDescGZIP(), []int{2}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetGoodId() string {
	if x != nil {
		return x.GoodId
	}
	return ""
}

func (x *Item) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type DeliveryPeriod struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          int32                  `protobuf:"varint,1,opt,name=from,proto3" json:"from,omitempty"`
	To            int32                  `protobuf:"varint,2,opt,name=to,proto3" json:"to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryPeriod) Reset() {
	*x = DeliveryPeriod{}
	mi := &file_api_basket_queues_basket_confirmed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryPeriod) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryPeriod) ProtoMessage() {}

func (x *DeliveryPeriod) ProtoReflect() protoreflect.Message {
	mi := &file_api_basket_queues_basket_confirmed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryPeriod.ProtoReflect.Descriptor instead.
func (*DeliveryPeriod) Descriptor() ([]byte, []int) {
	return file_api_basket_queues_basket_confirmed_proto_rawDescGZIP(), []int{3}
}

func (x *DeliveryPeriod) GetFrom() int32 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *DeliveryPeriod) GetTo() int32 {
	if x != nil {
		return x.To
	}
	return 0
}

var File_api_basket_queues_basket_confirmed_proto protoreflect.FileDescriptor

const file_api_basket_queues_basket_confirmed_proto_rawDesc = "" +
	"\n" +
	"(api/basket/queues/basket_confirmed.proto\x12\x0fBasketConfirmed\"\xe7\x01\n" +
	"\x1fBasketConfirmedIntegrationEvent\x12\x1a\n" +
	"\bbasketId\x18\x01 \x01(\tR\bbasketId\x122\n" +
	"\aaddress\x18\x02 \x01(\v2\x18.BasketConfirmed.AddressR\aaddress\x12+\n" +
	"\x05items\x18\x03 \x03(\v2\x15.BasketConfirmed.ItemR\x05items\x12G\n" +
	"\x0edeliveryPeriod\x18\x04 \x01(\v2\x1f.BasketConfirmed.DeliveryPeriodR\x0edeliveryPeriod\"\x83\x01\n" +
	"\aAddress\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12\x16\n" +
	"\x06street\x18\x03 \x01(\tR\x06street\x12\x14\n" +
	"\x05house\x18\x04 \x01(\tR\x05house\x12\x1c\n" +
	"\tapartment\x18\x05 \x01(\tR\tapartment\"v\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06goodId\x18\x02 \x01(\tR\x06goodId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x05 \x01(\x05R\bquantity\"4\n" +
	"\x0eDeliveryPeriod\x12\x12\n" +
	"\x04from\x18\x01 \x01(\x05R\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\x05R\x02toB\x1aZ\x18queues/basketconfirmedpbb\x06proto3"

var (
	file_api_basket_queues_basket_confirmed_proto_rawDescOnce sync.Once
	file_api_basket_queues_basket_confirmed_proto_rawDescData []byte
)

func file_api_basket_queues_basket_confirmed_proto_rawDescGZIP() []byte {
	file_api_basket_queues_basket_confirmed_proto_rawDescOnce.Do(func() {
		file_api_basket_queues_basket_confirmed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_basket_queues_basket_confirmed_proto_rawDesc), len(file_api_basket_queues_basket_confirmed_proto_rawDesc)))
	})
	return file_api_basket_queues_basket_confirmed_proto_rawDescData
}

var file_api_basket_queues_basket_confirmed_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_basket_queues_basket_confirmed_proto_goTypes = []any{
	(*BasketConfirmedIntegrationEvent)(nil), // 0: BasketConfirmed.BasketConfirmedIntegrationEvent
	(*Address)(nil),                         // 1: BasketConfirmed.Address
	(*Item)(nil),                            // 2: BasketConfirmed.Item
	(*DeliveryPeriod)(nil),                  // 3: BasketConfirmed.DeliveryPeriod
}
var file_api_basket_queues_basket_confirmed_proto_depIdxs = []int32{
	1, // 0: BasketConfirmed.BasketConfirmedIntegrationEvent.address:type_name -> BasketConfirmed.Address
	2, // 1: BasketConfirmed.BasketConfirmedIntegrationEvent.items:type_name -> BasketConfirmed.Item
	3, // 2: BasketConfirmed.BasketConfirmedIntegrationEvent.deliveryPeriod:type_name -> BasketConfirmed.DeliveryPeriod
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_basket_queues_basket_confirmed_proto_init() }
func file_api_basket_queues_basket_confirmed_proto_init() {
	if File_api_basket_queues_basket_confirmed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_basket_queues_basket_confirmed_proto_rawDesc), len(file_api_basket_queues_basket_confirmed_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_basket_queues_basket_confirmed_proto_goTypes,
		DependencyIndexes: file_api_basket_queues_basket_confirmed_proto_depIdxs,
		MessageInfos:      file_api_basket_queues_basket_confirmed_proto_msgTypes,
	}.Build()
	File_api_basket_queues_basket_confirmed_proto = out.File
	file_api_basket_queues_basket_confirmed_proto_goTypes = nil
	file_api_basket_queues_basket_confirmed_proto_depIdxs = nil
}
