// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/delivery/queues/order_status_changed.proto

package orderstatuschangedpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderStatus int32

const (
	OrderStatus_None      OrderStatus = 0
	OrderStatus_Created   OrderStatus = 1
	OrderStatus_Assigned  OrderStatus = 2
	OrderStatus_Completed OrderStatus = 3
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "None",
		1: "Created",
		2: "Assigned",
		3: "Completed",
	}
	OrderStatus_value = map[string]int32{
		"None":      0,
		"Created":   1,
		"Assigned":  2,
		"Completed": 3,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_delivery_queues_order_status_changed_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_api_delivery_queues_order_status_changed_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_delivery_queues_order_status_changed_proto_rawDescGZIP(), []int{0}
}

type OrderStatusChangedIntegrationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	OrderStatus   OrderStatus            `protobuf:"varint,2,opt,name=orderStatus,proto3,enum=OrderStatusChanged.OrderStatus" json:"orderStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusChangedIntegrationEvent) Reset() {
	*x = OrderStatusChangedIntegrationEvent{}
	mi := &file_api_delivery_queues_order_status_changed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusChangedIntegrationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusChangedIntegrationEvent) ProtoMessage() {}

func (x *OrderStatusChangedIntegrationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_delivery_queues_order_status_changed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusChangedIntegrationEvent.ProtoReflect.Descriptor instead.
func (*OrderStatusChangedIntegrationEvent) Descriptor() ([]byte, []int) {
	return file_api_delivery_queues_order_status_changed_proto_rawDescGZIP(), []int{0}
}

func (x *OrderStatusChangedIntegrationEvent) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *OrderStatusChangedIntegrationEvent) GetOrderStatus() OrderStatus {
	if x != nil {
		return x.OrderStatus
	}
	return OrderStatus_None
}

var File_api_delivery_queues_order_status_changed_proto protoreflect.FileDescriptor

const file_api_delivery_queues_order_status_changed_proto_rawDesc = "" +
	"\n" +
	".api/delivery/queues/order_status_changed.proto\x12\x12OrderStatusChanged\"\x81\x01\n" +
	"\"OrderStatusChangedIntegrationEvent\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\tR\aorderId\x12A\n" +
	"\vorderStatus\x18\x02 \x01(\x0e2\x1f.OrderStatusChanged.OrderStatusR\vorderStatus*A\n" +
	"\vOrderStatus\x12\b\n" +
	"\x04None\x10\x00\x12\v\n" +
	"\aCreated\x10\x01\x12\f\n" +
	"\bAssigned\x10\x02\x12\r\n" +
	"\tCompleted\x10\x03B\x1dZ\x1bqueues/orderstatuschangedpbb\x06proto3"

var (
	file_api_delivery_queues_order_status_changed_proto_rawDescOnce sync.Once
	file_api_delivery_queues_order_status_changed_proto_rawDescData []byte
)

func file_api_delivery_queues_order_status_changed_proto_rawDescGZIP() []byte {
	file_api_delivery_queues_order_status_changed_proto_rawDescOnce.Do(func() {
		file_api_delivery_queues_order_status_changed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_delivery_queues_order_status_changed_proto_rawDesc), len(file_api_delivery_queues_order_status_changed_proto_rawDesc)))
	})
	return file_api_delivery_queues_order_status_changed_proto_rawDescData
}

var file_api_delivery_queues_order_status_changed_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_delivery_queues_order_status_changed_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_delivery_queues_order_status_changed_proto_goTypes = []any{
	(OrderStatus)(0), // 0: OrderStatusChanged.OrderStatus
	(*OrderStatusChangedIntegrationEvent)(nil), // 1: OrderStatusChanged.OrderStatusChangedIntegrationEvent
}
var file_api_delivery_queues_order_status_changed_proto_depIdxs = []int32{
	0, // 0: OrderStatusChanged.OrderStatusChangedIntegrationEvent.orderStatus:type_name -> OrderStatusChanged.OrderStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_delivery_queues_order_status_changed_proto_init() }
func file_api_delivery_queues_order_status_changed_proto_init() {
	if File_api_delivery_queues_order_status_changed_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_delivery_queues_order_status_changed_proto_rawDesc), len(file_api_delivery_queues_order_status_changed_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_delivery_queues_order_status_changed_proto_goTypes,
		DependencyIndexes: file_api_delivery_queues_order_status_changed_proto_depIdxs,
		EnumInfos:         file_api_delivery_queues_order_status_changed_proto_enumTypes,
		MessageInfos:      file_api_delivery_queues_order_status_changed_proto_msgTypes,
	}.Build()
	File_api_delivery_queues_order_status_changed_proto = out.File
	file_api_delivery_queues_order_status_changed_proto_goTypes = nil
	file_api_delivery_queues_order_status_changed_proto_depIdxs = nil
}
