// Code generated by mockery v2.52.3. DO NOT EDIT.

package in

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	in "github.com/victor-tsykanov/delivery/internal/core/ports/in"
)

// MockICreateOrderCommandHandler is an autogenerated mock type for the ICreateOrderCommandHandler type
type MockICreateOrderCommandHandler struct {
	mock.Mock
}

type MockICreateOrderCommandHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockICreateOrderCommandHandler) EXPECT() *MockICreateOrderCommandHandler_Expecter {
	return &MockICreateOrderCommandHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: _a0, _a1
func (_m *MockICreateOrderCommandHandler) Handle(_a0 context.Context, _a1 in.CreateOrderCommand) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, in.CreateOrderCommand) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockICreateOrderCommandHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockICreateOrderCommandHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 in.CreateOrderCommand
func (_e *MockICreateOrderCommandHandler_Expecter) Handle(_a0 interface{}, _a1 interface{}) *MockICreateOrderCommandHandler_Handle_Call {
	return &MockICreateOrderCommandHandler_Handle_Call{Call: _e.mock.On("Handle", _a0, _a1)}
}

func (_c *MockICreateOrderCommandHandler_Handle_Call) Run(run func(_a0 context.Context, _a1 in.CreateOrderCommand)) *MockICreateOrderCommandHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(in.CreateOrderCommand))
	})
	return _c
}

func (_c *MockICreateOrderCommandHandler_Handle_Call) Return(_a0 error) *MockICreateOrderCommandHandler_Handle_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockICreateOrderCommandHandler_Handle_Call) RunAndReturn(run func(context.Context, in.CreateOrderCommand) error) *MockICreateOrderCommandHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockICreateOrderCommandHandler creates a new instance of MockICreateOrderCommandHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockICreateOrderCommandHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockICreateOrderCommandHandler {
	mock := &MockICreateOrderCommandHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
