// Code generated by mockery v2.52.3. DO NOT EDIT.

package in

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	in "github.com/victor-tsykanov/delivery/internal/core/ports/in"
)

// MockIGetPendingOrdersQueryHandler is an autogenerated mock type for the IGetPendingOrdersQueryHandler type
type MockIGetPendingOrdersQueryHandler struct {
	mock.Mock
}

type MockIGetPendingOrdersQueryHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIGetPendingOrdersQueryHandler) EXPECT() *MockIGetPendingOrdersQueryHandler_Expecter {
	return &MockIGetPendingOrdersQueryHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function with given fields: ctx
func (_m *MockIGetPendingOrdersQueryHandler) Handle(ctx context.Context) ([]*in.Order, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 []*in.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*in.Order, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*in.Order); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*in.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIGetPendingOrdersQueryHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockIGetPendingOrdersQueryHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIGetPendingOrdersQueryHandler_Expecter) Handle(ctx interface{}) *MockIGetPendingOrdersQueryHandler_Handle_Call {
	return &MockIGetPendingOrdersQueryHandler_Handle_Call{Call: _e.mock.On("Handle", ctx)}
}

func (_c *MockIGetPendingOrdersQueryHandler_Handle_Call) Run(run func(ctx context.Context)) *MockIGetPendingOrdersQueryHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockIGetPendingOrdersQueryHandler_Handle_Call) Return(_a0 []*in.Order, _a1 error) *MockIGetPendingOrdersQueryHandler_Handle_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIGetPendingOrdersQueryHandler_Handle_Call) RunAndReturn(run func(context.Context) ([]*in.Order, error)) *MockIGetPendingOrdersQueryHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIGetPendingOrdersQueryHandler creates a new instance of MockIGetPendingOrdersQueryHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIGetPendingOrdersQueryHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIGetPendingOrdersQueryHandler {
	mock := &MockIGetPendingOrdersQueryHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
